# Generated by Django 2.2 on 2019-04-29 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=7)),
                ('iconName', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Obstacle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OvercomePlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('obstacle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Obstacle')),
            ],
        ),
        migrations.CreateModel(
            name='Habbit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('wish', models.TextField()),
                ('outcome', models.TextField()),
                ('category', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Category')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Customer')),
                ('obstacles', models.ManyToManyField(to='api.Obstacle')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('privacy_level', models.CharField(choices=[('PR', 'Личный'), ('PB', 'Публичный')], default='PR', max_length=2)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Customer')),
            ],
        ),
    ]
